language: android
# Currently android projects are only supported in trusty, as per:
# https://docs.travis-ci.com/user/languages/android/#overview
# If this language is not there, try uncommenting: 
# "Android builds are only supported on our Trusty image at this time ..."
dist: trusty

jdk:
  - oraclejdk8
  - openjdk11

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

before_install:
  - if [[ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]]; then yes | sdkmanager "platforms;android-28"; fi

script:
  - if [[ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]]; then ./gradlew verGJF build; fi
  - if [[ "$TRAVIS_JDK_VERSION" == "openjdk11" ]]; then ./gradlew :nullaway:test; fi

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
